### ISSUE TITLE
Question: Why does not lwan use epoll on Main-Socket

### ISSUE THREAD

**Issue by Liuchang0812** [lpereira/lwan#161]
As we know, We could use `epoll_ctl` to add main-socket to `epoll file description` for which we could get event when new socket is ready to `accept`. Why does `lwan` use blocking `accept4` for main-socket?

Any comment is appreciated.

**Comment by lpereira** [comment]
The main socket used to be non-blocking and Lwan would block on `epoll_wait()` instead. By using blocking I/O on the main socket, this cuts the amount of system calls that are performed to accept a connection.

I've been meaning to add the main socket to each I/O thread's epoll set for a while, though, so that the main thread would be mostly just sleeping, blocked on `pthread_join()`.  I'm not sure if the CPU migration of the main socket would improve or hurt the performance, though.  Also, the scheduler which picks which thread that'll handle a connection does require shared state on architectures other than x86-64, which requires a bit of care before making this change (atomic increments should be enough).

In general, there's a few of things that can be improved in the acceptor thread design.

**Comment by Liuchang0812** [comment]
Thanks @lpereira :+1:

**Comment by lpereira** [comment]
I'm closing the issue. Feel free to reopen it or open another one.
