### ISSUE TITLE
any c script like scripting possibility without garbage collection (or with) that can be used on lwan?

### ISSUE THREAD

**Issue by superdolt** [lpereira/lwan#313]
any c script like scripting possibility without garbage collection (or with) that can be used on lwan?

**Comment by lpereira** [comment]
Nothing that's supported by default, but it should be fairly easy to
add support for something, as long as:

1. The interpreter state is not global, so that we can create a new
state for each request
2. You can use the interpreter as a library linked to a C program
3. You write a module, like lwan-mod-lua, that allows you to program
things using that language as well

On Sun, Sep 12, 2021 at 1:18 PM superdolt ***@***.***> wrote:
>
> any c script like scripting possibility without garbage collection (or with) that can be used on lwan?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 
 Leandro

**Comment by superdolt** [comment]
ok thx.
