### ISSUE TITLE
Memory leaks in lwan

### ISSUE THREAD

**Issue by ryancaicse** [lpereira/lwan#324]
The memory block created at Line 125 is leaked in the method `parse_listener_prefix`.
https://github.com/lpereira/lwan/blob/2f34d6ff3fa4cbb4a78e274e09cdf029ebb7c77d/src/lib/lwan.c#L125-L139
https://github.com/lpereira/lwan/blob/2f34d6ff3fa4cbb4a78e274e09cdf029ebb7c77d/src/lib/lwan.c#L400-L404

**Comment by lpereira** [comment]
Where's the memory leak?

**Comment by lpereira** [comment]
There's no memory leak in this function. The memory is now owned by the
trie, which will call destroy_urlmap() and free the memory. Unless there's
a bug in the trie data structure, of course.

Are you using some static analysis tool to find these? Because if you are,
these tools can be wrong most of the time, especially when "ownership" is
passed around like this and function pointers are called to free the memory.

**Comment by ryancaicse** [comment]
@lpereira Sorry, when I take a close look, it seems it's wrong.
